#!/usr/bin/python3

from skill import Skill
from skill_names import SkillNames
from attributes import Attributes

swordArts = Skill(SkillNames.SWORD_ARTS, Attributes.HP, Attributes.STRENGTH, Attributes.STRENGTH, Attributes.AGILITY)
martialArts = Skill(SkillNames.MARTIAL_ARTS, Attributes.HP, Attributes.STRENGTH, Attributes.ENDURANCE, Attributes.AGILITY)
staffArts = Skill(SkillNames.STAFF_ARTS, Attributes.HP, Attributes.STRENGTH, Attributes.ENDURANCE, Attributes.MAGIC)
defenseArts = Skill(SkillNames.DEFENSE_ARTS, Attributes.HP, Attributes.HP, Attributes.ENDURANCE, Attributes.ENDURANCE)
kiArts = Skill(SkillNames.KI_ARTS, Attributes.MP, Attributes.MP, Attributes.ENDURANCE, Attributes.DEXTERITY)
throwing = Skill(SkillNames.THROWING, Attributes.STRENGTH, Attributes.STRENGTH, Attributes.DEXTERITY, Attributes.DEXTERITY)
strongShoulder = Skill(SkillNames.STRONG_SHOULDER, Attributes.STRENGTH, Attributes.STRENGTH, Attributes.STRENGTH, Attributes.DEXTERITY)
armor = Skill(SkillNames.ARMOR, Attributes.ENDURANCE, Attributes.ENDURANCE, Attributes.ENDURANCE, Attributes.ENDURANCE)
hardBones = Skill(SkillNames.HARD_BONES, Attributes.STRENGTH, Attributes.ENDURANCE, Attributes.ENDURANCE, Attributes.ENDURANCE)
regen = Skill(SkillNames.REGEN, Attributes.HP, Attributes.HP, Attributes.ENDURANCE, Attributes.LUCK)
evasion = Skill(SkillNames.EVASION, Attributes.AGILITY, Attributes.AGILITY, Attributes.AGILITY, Attributes.DEXTERITY)
escape = Skill(SkillNames.ESCAPE, Attributes.AGILITY, Attributes.AGILITY, Attributes.AGILITY, Attributes.LUCK)
instantaneousForce = Skill(SkillNames.INSTANTANEOUS_FORCE, Attributes.STRENGTH, Attributes.AGILITY, Attributes.AGILITY, Attributes.AGILITY)
jump = Skill(SkillNames.JUMP, Attributes.AGILITY, Attributes.AGILITY, Attributes.DEXTERITY, Attributes.DEXTERITY)
swimming = Skill(SkillNames.SWIMMING, Attributes.HP, Attributes.HP, Attributes.STRENGTH, Attributes.AGILITY)
fireMagic = Skill(SkillNames.FIRE_MAGIC, Attributes.MP, Attributes.MAGIC, Attributes.MAGIC, Attributes.INTELLIGENCE)
waterMagic = Skill(SkillNames.WATER_MAGIC, Attributes.MP, Attributes.MAGIC, Attributes.MAGIC, Attributes.INTELLIGENCE)
earthMagic = Skill(SkillNames.EARTH_MAGIC, Attributes.MP, Attributes.MAGIC, Attributes.MAGIC, Attributes.INTELLIGENCE)
windMagic = Skill(SkillNames.WIND_MAGIC, Attributes.MP, Attributes.MAGIC, Attributes.MAGIC, Attributes.INTELLIGENCE)
lightningMagic = Skill(SkillNames.LIGHTNING_MAGIC, Attributes.MP, Attributes.MAGIC, Attributes.MAGIC, Attributes.INTELLIGENCE)
darkMagic = Skill(SkillNames.DARK_MAGIC, Attributes.MP, Attributes.MAGIC, Attributes.MAGIC, Attributes.INTELLIGENCE)
lightMagic = Skill(SkillNames.LIGHT_MAGIC, Attributes.MP, Attributes.MAGIC, Attributes.MAGIC, Attributes.INTELLIGENCE)
sharpening = Skill(SkillNames.SHARPENING, Attributes.STRENGTH, Attributes.DEXTERITY, Attributes.DEXTERITY, Attributes.DEXTERITY)
magicWeapon = Skill(SkillNames.MAGIC_WEAPON, Attributes.MP, Attributes.STRENGTH, Attributes.MAGIC, Attributes.MAGIC)
magicPreservation = Skill(SkillNames.MAGIC_PRESERVATION, Attributes.MP, Attributes.MP, Attributes.MAGIC, Attributes.MAGIC)
magicPowerDetection = Skill(SkillNames.MAGIC_POWER_DETECTION, Attributes.MAGIC, Attributes.LUCK, Attributes.LUCK, Attributes.LUCK)
presenceDetection = Skill(SkillNames.PRESENCE_DETECTION, Attributes.DEXTERITY, Attributes.LUCK, Attributes.LUCK, Attributes.LUCK)
dangerDetection = Skill(SkillNames.DANGER_DETECTION, Attributes.AGILITY, Attributes.LUCK, Attributes.LUCK, Attributes.LUCK)
intuition = Skill(SkillNames.INTUITION, Attributes.INTELLIGENCE, Attributes.LUCK, Attributes.LUCK, Attributes.LUCK)
heartEye = Skill(SkillNames.HEART_EYE, Attributes.DEXTERITY, Attributes.DEXTERITY, Attributes.LUCK, Attributes.LUCK)
protection = Skill(SkillNames.PROTECTION, Attributes.ENDURANCE, Attributes.MAGIC, Attributes.MAGIC, Attributes.LUCK)
calculation = Skill(SkillNames.CALCULATION, Attributes.INTELLIGENCE, Attributes.INTELLIGENCE, Attributes.INTELLIGENCE, Attributes.INTELLIGENCE)
commander = Skill(SkillNames.COMMANDER, Attributes.INTELLIGENCE, Attributes.INTELLIGENCE, Attributes.DEXTERITY, Attributes.DEXTERITY)
willpower = Skill(SkillNames.WILLPOWER, Attributes.HP, Attributes.STRENGTH, Attributes.ENDURANCE, Attributes.ENDURANCE)
encouragement = Skill(SkillNames.ENCOURAGEMENT, Attributes.STRENGTH, Attributes.STRENGTH, Attributes.ENDURANCE, Attributes.ENDURANCE)
teaching = Skill(SkillNames.TEACHING, Attributes.INTELLIGENCE, Attributes.DEXTERITY, Attributes.DEXTERITY, Attributes.DEXTERITY)
cooking = Skill(SkillNames.COOKING, Attributes.STRENGTH, Attributes.DEXTERITY, Attributes.DEXTERITY, Attributes.LUCK)
maintenance = Skill(SkillNames.MAINTENANCE, Attributes.INTELLIGENCE, Attributes.INTELLIGENCE, Attributes.DEXTERITY, Attributes.DEXTERITY)
dismantling = Skill(SkillNames.DISMANTLING, Attributes.DEXTERITY, Attributes.DEXTERITY, Attributes.DEXTERITY, Attributes.DEXTERITY)
pleasantSleep = Skill(SkillNames.PLEASANT_SLEEP, Attributes.HP, Attributes.HP, Attributes.ENDURANCE, Attributes.ENDURANCE)
theft = Skill(SkillNames.THEFT, Attributes.AGILITY, Attributes.DEXTERITY, Attributes.DEXTERITY, Attributes.LUCK)
bigEater = Skill(SkillNames.BIG_EATER, Attributes.HP, Attributes.HP, Attributes.ENDURANCE, Attributes.LUCK)
lucky = Skill(SkillNames.LUCKY, Attributes.LUCK, Attributes.LUCK, Attributes.LUCK, Attributes.LUCK)
fireResistance = Skill(SkillNames.FIRE_RESISTANCE, Attributes.HP, Attributes.ENDURANCE, Attributes.MAGIC, Attributes.INTELLIGENCE)
coldResistance = Skill(SkillNames.COLD_RESISTANCE, Attributes.HP, Attributes.HP, Attributes.ENDURANCE, Attributes.ENDURANCE)
lightningResistance = Skill(SkillNames.LIGHTNING_RESISTANCE, Attributes.HP, Attributes.ENDURANCE, Attributes.MAGIC, Attributes.INTELLIGENCE)

