#!/usr/bin/python3

from enum import Enum

class SkillNames(Enum):
    SWORD_ARTS = 1
    MARTIAL_ARTS = 2
    STAFF_ARTS = 3
    DEFENSE_ARTS = 4
    KI_ARTS = 5
    THROWING = 6
    STRONG_SHOULDER = 7
    ARMOR = 8
    HARD_BONES = 9
    REGEN = 10
    EVASION = 11
    ESCAPE = 12
    INSTANTANEOUS_FORCE = 13
    JUMP = 14
    SWIMMING = 15
    FIRE_MAGIC = 16
    WATER_MAGIC = 17
    EARTH_MAGIC = 18
    WIND_MAGIC = 19
    LIGHTNING_MAGIC = 20
    DARK_MAGIC = 21
    LIGHT_MAGIC = 22
    SHARPENING = 23
    MAGIC_WEAPON = 24
    MAGIC_PRESERVATION = 25
    MAGIC_POWER_DETECTION = 26
    PRESENCE_DETECTION = 27
    DANGER_DETECTION = 28
    INTUITION = 29
    HEART_EYE = 30
    PROTECTION = 31
    CALCULATION = 32
    COMMANDER = 33
    WILLPOWER = 34
    ENCOURAGEMENT = 35
    TEACHING = 36
    COOKING = 37
    MAINTENANCE = 38
    DISMANTLING = 39
    PLEASANT_SLEEP = 40
    THEFT = 41
    BIG_EATER = 42
    LUCKY = 43
    FIRE_RESISTANCE = 44
    COLD_RESISTANCE = 45
    LIGHTNING_RESISTANCE = 46


